### ISSUE TITLE
Can't find plugin

### ISSUE THREAD

**Issue by jsnrynlds** [phosphor-icons/phosphor-sketch#5]
Hello – this looks awesome, but the link in `README.md` is to the Figma page and the plugin isn't included on the [Sketch website](https://www.sketch.com/extensions/plugins/) yet.

**Comment by rektdeckard** [comment]
Link has been updated! You can always find it in https://github.com/phosphor-icons/phosphor-sketch/releases

**Comment by rektdeckard** [comment]
We're still waiting for acceptance to the website :)

**Comment by jsnrynlds** [comment]
Thanks @rektdeckard!
